name: Swift Benchmark

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
      - name: Run benchmarks
        id: benchmark
        run: |
          echo $(date) >> $GITHUB_STEP_SUMMARY
          swift package benchmark --format markdown >> $GITHUB_STEP_SUMMARY
      - name: Pull request comment text
        id: prtest
        run: |
          echo 'PRTEST<<EOF' >> $GITHUB_ENV
          echo "[Pull request benchmark baseline run at $(date -Iseconds)](https://github.com/ordo-one/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV          
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.CI_MACHINE_PAT }}
          message: ${{ env.PRTEST }}
          comment_includes: "Benchmark baseline last run at"
          
