name: Swift Benchmark delta vs main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  benchmark-delta:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install sudo package
      run: apt update && apt install sudo
    - name: Install libjemalloc
      run: sudo apt-get install -y libjemalloc-dev
    - run: echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
    - name: Run benchmarks
      run: swift package --allow-writing-to-directory .benchmarkBaselines/ benchmark update-baseline pull_request
    - name: Switch to main
      run: git checkout main
    - name: Run benchmarks for main
      run: swift package --allow-writing-to-directory .benchmarkBaselines/ benchmark update-baseline main
    - name: Compare benchmarks
      id: benchmark
      run: |
        echo 'BENCHMARK<<EOF' >> $GITHUB_ENV
        swift package benchmark compare main pull_request --format markdown >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        GITHUB_TOKEN: ${{ secrets.CI_MACHINE_PAT }}
        message: ${{ env.BENCHMARK }}
        comment_includes: 'Comparing results'
